### PR TITLE
Travis CI: Add Python 3.7 to the testing

### PR DESCRIPTION
**Pull request by cclauss**
* Add Python 3.7 to the testing In alignment with travis-ci/travis-ci#9069
* Tox no longer supports the EOLed Python 3.3.
* Lint on Python 3 instead of Python 2 because it is stricter.

### CODE REVIEW

**Comment by illfelder** [comment]
Please update the PR to diff against our development branch. Once that's all taken care of we can merge this in (assuming the tests pass).

**Comment by illfelder** [comment]
Please clean up the commits so that your PR only includes your change in the commit history. Also, why allow failures for python 3.7?

**Comment by cclauss** [comment]
Tests fail on Python 3.7.  I do not have the knowledge/skills to fix them but showing the to others will provide visibility to get them fixed.  This is described in the Travis docs.

**Comment by illfelder** [comment]
Okay, thanks! Once the commits are cleaned up we can merge this in.

**Comment by cclauss** [comment]
Closed in favor of #648 which has no merge conflicts.

**Pull request closed without merging**
