### PR TITLE
Updating travis to use tox

### LINKED ISSUE #275: Create tox configuration to handle testing multiple Python environments
We should use [tox](https://tox.readthedocs.io/en/latest/) to test in multiple Python environments. Travis should just call into tox.

### PR DESCRIPTION
**Pull request by jonparrott**
Fixes #275 and #276 and starts on #274.

@illfelder PTAL

### CODE REVIEW

**Comment by illfelder** [comment]
Awesome! After the tests are passing again, please squash the commits. Let's push this to the development branch instead of master.

**Comment by jonparrott** [comment]
> After the tests are passing again

Some wonkiness with py3.2 - is it critical to support that version? Pip itself does not.

> please squash the commits

github can do that when merging.

> Let's push this to the development branch instead of master.

No problem.

**Comment by jonparrott** [comment]
@illfelder Travis is passing. We can merge when you're satisfied. Do you want to merge this to master or develop?

**Comment by illfelder** [comment]
Great! Let's merge to the development branch. We'll move it to master during our next release.

**Comment by jonparrott** [comment]
Cool, closing this PR and opening another against develop and will merge.

**Pull request closed without merging**
