### PR TITLE
Unified docs and repo settings

### PR DESCRIPTION
**Pull request by renich**
I've unified what the docs say at: https://developers.google.com/compute/docs/images#kernelsecurity and what you have in your repo.

Also, the settings are sorted.

### CODE REVIEW

**Comment by zmarano** [comment]
If this is still relevant, feel free to re-open and also submit a CLA (https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/CONTRIB.md). Marking as closed for now.

**Comment by renich** [comment]
The CLA is signed. I dunno how to submit it.

It should be relevant. It's cleaner code for the kernel settings.

**Comment by zmarano** [comment]
Oh I'm sorry, yes you do have a CLA. We'll take a closer look at this PR and get back soon.

**Comment by illfelder** [comment]
Closing this off - we looked more closely at the pull request and decided we shouldn't make kernel setting changes to our base images by default.

**Pull request closed without merging**
