### PR TITLE
Add systemd as valid ntp daemon

### PR DESCRIPTION
**Pull request by GMLudo**
Hi,

We are using **systemd-timesyncd** as NTP daemon.
Could you add systemd as valid NTP daemon in the debian package ?

Thanks.

### CODE REVIEW

**Comment by GMLudo** [comment]
I signed it!

**Comment by GMLudo** [comment]
Hi,

The error in travis-ci seems unrelated with my modification.

Thanks for the merge.

**Comment by illfelder** [comment]
Thanks for the contribution! Please update the pull request to diff against the development branch. That will also resolve the travis errors.

**Comment by GMLudo** [comment]
I have made a mistake with this PR.
I have opened a new one: #523

**Pull request closed without merging**
