### PR TITLE
Adjust tests to changed LoadJsonArrayToCache() behaviour

### PR DESCRIPTION
**Pull request by rbalint**
The change was committed in 0bd54db18db9b78e480f70ee1611df3914da13f0

### CODE REVIEW

**Comment by zmarano** [comment]
Hi Balint, if you sign the CLA we can merge this PR in. The instructions are in the message there.

**Comment by rbalint** [comment]
Hi Zach,
Yes, I read the instructions and there is an already started company process to get the CLA signed for me, I'm waiting for that to finish.

**Comment by zmarano** [comment]
Great, no worries. Thanks!

**Comment by illfelder** [comment]
What's the status of the CLA stuff? I'd like to merge this in before our next release cut if possible.

**Comment by rbalint** [comment]
@illfelder I just got the info that we already sent the formal request to Google to add me to the list of allowed contributors. We are waiting for the request to be accepted by Google.

**Comment by rbalint** [comment]
Our company representative has signed the CLA for me.

**Comment by illfelder** [comment]
I'm not sure why the CLA hasn't updated, but regardless you should be considered part of the Canonical CLA. I overrode the CLA check. Please update your PR and I'll merge it in.

**Comment by rbalint** [comment]
Our company representative has signed the CLA for me.

**Comment by illfelder** [comment]
I've fixed travis so your PR should pass now. Please update your branch, then I'll mark the CLA as signed and merge.

**Pull request merged**
