### PR TITLE
Use curl to download metadata script files.

### PR DESCRIPTION
**Pull request by illfelder**
In Python 2.6, urllib does not check ssl certificates.

### CODE REVIEW

**Comment by zmarano** [comment]
Add a requirement for curl to the package files:
https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/specs/google-compute-engine.spec#L34
https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/debian/control#L22

**Comment by illfelder** [comment]
Added dependency.

**Comment by wonderfly** [comment]
lgtm

**Pull request merged**
