### PR TITLE
Add 120s timeout so Ubuntu 15+ doesn't timeout on shutdown scripts ea…

### PR DESCRIPTION
**Pull request by null0000**
…rly after 90s

### CODE REVIEW

**Comment by illfelder** [comment]
This is not a change we want to make. We should not limit the time a shutdown script has to run.

**Comment by null0000** [comment]
We need to specify a timeout to avoid having shutdown problems on Ubuntu.
As is, it shuts down at 90 seconds because of systemd defaults. Two minutes
is the duration vms stay up after being told to shut down, so having
timeout=120 makes sense

I can try timeout=0, but it's effectively the same thing from the users
perspective, unless we have vms staying up past two minutes once the vm is
shut down.

**Comment by illfelder** [comment]
A VM has no shutdown time limit when shutdown is triggered from the guest (or any other guest operations). This is also the case for reboot.

**Comment by null0000** [comment]
Fair enough. I'll change it

**Comment by null0000** [comment]
Fixed. Tests passing on Debian and Ubuntu

**Comment by illfelder** [comment]
LGTM.

**Pull request merged**
