### PR TITLE
allow other paths for nologin

### PR DESCRIPTION
**Pull request by zimbatm**
Hi,

I am integrating these tools to the NixOS GCE image (see https://github.com/NixOS/nixpkgs/pull/26214) and this is one of the patches required to make it work. I also had to patch a couple of hard-coded binary paths. Other than that it was pretty easy to integrate. Dynamic SSH keys, disks and metadata startup/shutdown scripts are all working. I haven't tested the IP forwarding.

Going forwards I am interested to see how we could collaborate to keep the NixOS integration working with new features.

Best,
z

### CODE REVIEW

**Comment by zimbatm** [comment]
It looks like the CI failure is unrelated to this submission. The python 3.6 build has an empty log.

**Comment by illfelder** [comment]
Hi @zimbatm, thanks for your contribution!

We need to validate that these changes won't break on other Linux distributions before we can merge. It's possible that the pw_entry may need to include a full path to work properly on EL distros or Debian based ones.

With regard to the broken continuous test, it's a travis issue that's fixed in the development branch. We ask that all guest changes are made to the development branch rather than master. We promote them to master when we publish a release candidate.

**Comment by zimbatm** [comment]
Hi @illfelder, thanks!

Do you have automated tests or a manual test plan that I can use against NixOS?

I rebased the branch on top of development, let's see if the tests are going to pass this time.

**Comment by illfelder** [comment]
Thanks for updating the pull request! We'll take care of the validation (we will need to run the changes against integration tests) but it might take a little while before we have the chance.

**Comment by zimbatm** [comment]
@illfelder rebased the change on the latest development. Is there anything I can do to help this get accepted?

**Comment by illfelder** [comment]
Thanks for the ping! Changes looks good to me, so I'll merge it in.

**Pull request merged**
