### PR TITLE
Add lint to Travis

### LINKED ISSUE #357: Enable linter to automatically run against pull requests

### PR DESCRIPTION
**Pull request by jonparrott**
Resolves #357

### CODE REVIEW

**Comment by illfelder** [comment]
Awesome! Will this check for google-style compliance? Or just ignore the pep-8 compliance checks that differ from google style?

**Comment by jonparrott** [comment]
[Google (public) style](https://google.github.io/styleguide/pyguide.html) *is* pep8. This package currently follows Google *internal* style.

We should work to remove the `ignore`d warnings after this is merged.

**Comment by illfelder** [comment]
Sounds good. Before I merge, can you change this PR to be against the development branch rather than master?

**Comment by jonparrott** [comment]
Changed the base but it pull in a bunch of stuff, let me re-base.

**Comment by jonparrott** [comment]
Rebased, should be good to go.

**Pull request merged**
